/// Flutter icons StatIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StatIcons
///      fonts:
///       - asset: fonts/StatIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StatIcons {
  StatIcons._();

  static const _kFontFam = 'StatIcons';

  static const IconData abilitypower = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData armor = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData attackdamage = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData attackspeed = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData health = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData magicresist = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData mana = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData gold = const IconData(0xe807, fontFamily: _kFontFam);
}
